---
version: 1
enabled: true
comment_template_file: ".stoat/template.hbs"
plugins:
  app-test-coverage:
    metadata:
      name: "`app` test coverage"
    static_hosting:
      path: backend/app/build/reports/html/jacoco
  list-test-coverage:
    metadata:
      name: "`list` test coverage"
    static_hosting:
      path: backend/list/build/reports/html/jacoco
  frontend-storybook:
    metadata:
      name: storybook
    static_hosting:
      path: frontend/storybook-static
  gradle-build-time:
    json:
      path: gradle-build-time.json
