hosting:
  static:
    app_test_coverage:
      name: "`app` test coverage"
      path: examples/app/build/reports/html/jacoco
    lib_test_coverage:
      name: "`lib` test coverage"
      path: examples/lib/build/reports/html/jacoco
    docs:
      name: docs
      path: docs/build
    frontend:
      name: storybook
      path: examples/frontend/storybook-static
comment_template: ".stoat/template.hbs"
