---
version: 1
enabled: true
comment_template: ".stoat/template.hbs"
plugins:
  app-test-coverage:
    metadata:
      name: "`app` test coverage"
    static_hosting:
      path: examples/backend/app/build/reports/html/jacoco
  list-test-coverage:
    metadata:
      name: "`list` test coverage"
    static_hosting:
      path: examples/backend/list/build/reports/html/jacoco
  frontend-storybook:
    metadata:
      name: storybook
    static_hosting:
      path: examples/frontend/storybook-static
