name: Backend

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Record Start Time
        run: |
          date +%s > start.txt

      - name: Build Gradle Project
        run: |
          cd backend
          ./gradlew build jacocoTestReport

      - name: Calculate Gradle Build Time
        run: |
          echo "{ \"seconds\": `expr $(date +%s) - $(cat start.txt)` }" > gradle-build-time.json

      - name: Run Stoat Action
        uses: stoat-dev/stoat-action@v0
        if: always()
