name: Check DB Schema

on:
  push:
    branches: [ main ]
    paths:
      - 'supabase/migrations/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'supabase/migrations/**'
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/site/node_modules
            ${{ github.workspace }}/site/.next/cache
          key: ${{ runner.os }}-node-16-${{ hashFiles('site/yarn.lock') }}
      - name: Install supabase
        uses: supabase/setup-cli@v1
        with:
          version: 1.0.0
      - name: Launch supabase local instance
        run: supabase start
      - name: Verify generated database types
        run: |
          cd site
          yarn install --frozen-lockfile
          yarn db:schema
          yarn prettier:write
          if [ "$(git diff --ignore-space-at-eol src/db/schema.gen.ts | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted database changes. See status below:"
            git diff
            exit 1
          fi
