name: Frontend

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build Frontend App
        run: |
          cd examples/frontend
          npm install
          npm run build

      - name: Build Storybook
        run: |
          cd examples/frontend
          npm run build-storybook
